/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Candidates */
        get: operations["list_candidates_api_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Batch
         * @description Which branch the next promotion lands on, and how much is already queued there.
         */
        get: operations["get_batch_api_candidates_batch_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candidate */
        get: operations["get_candidate_api_candidates__candidate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Undo
         * @description Return a candidate to the queue. Undoing a promotion does not revert its commit — the branch
         *     is the record of what was proposed, and rewriting it silently would be worse than a duplicate.
         */
        delete: operations["undo_api_candidates__candidate_id__decision_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Promotion
         * @description Validate the edits and show exactly what would be committed. Writes nothing.
         *
         *     Lets the console surface a `SkillLoadError` against the field that caused it while the person
         *     is still editing, instead of after the commit.
         */
        post: operations["preview_promotion_api_candidates__candidate_id__preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote */
        post: operations["promote_api_candidates__candidate_id__promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_api_candidates__candidate_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Console Config */
        get: operations["get_console_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/git/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose
         * @description Publish a branch.
         *
         *     Pushing is never implicit — this route exists so that it is always a deliberate action. Opening
         *     the merge request itself needs a provider implementing `WriteConnector`, which Milestone 1
         *     defines but does not implement; until one is registered this pushes the branch and says so
         *     rather than pretending a merge request was created.
         *
         *     A branch carrying a guidance change is refused unless a passing gate covers the exact content
         *     it would publish (C6). This is the choke point rather than the editor, because the editor is
         *     not the only way commits reach a branch.
         */
        post: operations["propose_api_git_propose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/git/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Git Status */
        get: operations["get_git_status_api_git_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Report
         * @description The standalone HTML `whetstone report` writes — shareable straight from the console.
         */
        get: operations["get_run_report_api_runs__run_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Skills
         * @description Every skill, weakest first — the console's landing order.
         */
        get: operations["list_skills_api_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skill */
        get: operations["get_skill_api_skills__skill_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skill_id}/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_api_skills__skill_id__cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skill_id}/guidance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Guidance
         * @description Stage a guidance edit on the skill's branch.
         */
        put: operations["put_guidance_api_skills__skill_id__guidance_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skill_id}/guidance/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Guidance
         * @description Validate an edit and return exactly what would be committed. Writes nothing.
         */
        post: operations["preview_guidance_api_skills__skill_id__guidance_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skill_id}/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Meta
         * @description Stage a `meta.yaml` edit — owner, references, and rule provenance.
         *
         *     Lands on the same branch as a guidance edit, so metadata and the rules it documents travel
         *     together. Never affects the C6 verdict: nothing in this file reaches the reviewer.
         */
        put: operations["put_meta_api_skills__skill_id__meta_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skill_id}/proposal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Proposal
         * @description What is staged for this skill, and whether it may be published (C6).
         */
        get: operations["get_proposal_api_skills__skill_id__proposal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddedLine
         * @description A line introduced by the change, with its line number in the new file.
         */
        AddedLine: {
            /** Content */
            content: string;
            /** Line */
            line: number;
        };
        /** BackendInfo */
        BackendInfo: {
            /** Base Url */
            base_url?: string | null;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Name */
            name: string;
        };
        /**
         * Batch
         * @description An accumulating branch of promoted cases, and whether it is still open.
         */
        Batch: {
            /** Branch */
            branch: string;
            /** Commits */
            commits: number;
            /** Exists */
            exists: boolean;
            /** Proposed */
            proposed: boolean;
        };
        /**
         * CandidateCase
         * @description A proposed eval case derived from review history. The corpus builder emits these; a human
         *     reviews, routes, and promotes them into a skill's `eval_cases/`. Nothing is auto-adopted.
         */
        CandidateCase: {
            change: components["schemas"]["CodeChange"];
            /** Confidence */
            confidence: number;
            /** Expect */
            expect: components["schemas"]["Expectation"][];
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "should_catch" | "should_not_flag";
            provenance: components["schemas"]["Provenance"];
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /** Suggested Skill */
            suggested_skill?: string | null;
        };
        /**
         * CandidateEntry
         * @description A candidate plus its diff and decision — everything the triage screen needs.
         */
        CandidateEntry: {
            candidate: components["schemas"]["CandidateCase"];
            decision?: components["schemas"]["Decision"] | null;
            /**
             * Diff
             * @default
             */
            diff: string;
        };
        /** CaseDetail */
        CaseDetail: {
            case: components["schemas"]["EvalCase"];
            /** Diff */
            diff: string;
            /**
             * History
             * @default []
             */
            history: components["schemas"]["CaseHistoryEntry"][];
            /** Skill Id */
            skill_id: string;
        };
        /**
         * CaseEdits
         * @description The human's corrections to a candidate, applied before it becomes an eval case.
         */
        CaseEdits: {
            /** Case Id */
            case_id: string;
            /**
             * Expectation Id
             * @default e1
             */
            expectation_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "should_catch" | "should_not_flag";
            /** Line Range */
            line_range?: [
                number,
                number
            ] | null;
            /** Path */
            path: string;
            /**
             * Rule Id
             * @default
             */
            rule_id: string;
            /**
             * Semantic
             * @default
             */
            semantic: string;
            severity_min?: components["schemas"]["Severity"] | null;
            /** Skill Id */
            skill_id: string;
        };
        /** CaseHistoryEntry */
        CaseHistoryEntry: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Flaky */
            flaky: boolean;
            /** Fp Rate */
            fp_rate: number;
            /** Recall */
            recall: number;
            /** Run Id */
            run_id: string;
        };
        /**
         * CaseRun
         * @description Every trial of one eval case.
         */
        CaseRun: {
            /** Case Id */
            case_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "should_catch" | "should_not_flag";
            /**
             * Trials
             * @default []
             */
            trials: components["schemas"]["TrialRecord"][];
        };
        /**
         * CaseScore
         * @description Per-eval-case result: one Confusion per trial, plus the aggregate.
         */
        CaseScore: {
            /** Case Id */
            case_id: string;
            readonly confusion: components["schemas"]["Confusion"];
            /** Fp Rate */
            readonly fp_rate: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "should_catch" | "should_not_flag";
            /** Recall */
            readonly recall: number;
            /** Trials */
            trials: components["schemas"]["Confusion"][];
        };
        /**
         * CaseSummary
         * @description One eval case as it appears in a list, enriched with how it last behaved.
         */
        CaseSummary: {
            /**
             * Expectations
             * @default 0
             */
            expectations: number;
            /**
             * Flaky
             * @default false
             */
            flaky: boolean;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "should_catch" | "should_not_flag";
            /** Last Fp Rate */
            last_fp_rate?: number | null;
            /** Last Recall */
            last_recall?: number | null;
            /**
             * Path
             * @default
             */
            path: string;
            /**
             * @default {
             *       "source": "manual"
             *     }
             */
            provenance: components["schemas"]["Provenance"];
        };
        /** CodeChange */
        CodeChange: {
            /**
             * Base Ref
             * @default
             */
            base_ref: string;
            /**
             * Files
             * @default []
             */
            files: components["schemas"]["FileChange"][];
            /**
             * Head Ref
             * @default
             */
            head_ref: string;
            repo: components["schemas"]["RepoRef"];
        };
        /**
         * Confusion
         * @description Confusion counts. `appear` expectations feed TP/FN; `not_appear` feed FP/TN.
         *
         *     Metric conventions (documented so a gate 'fail' is never an artifact of division):
         *       - recall    = TP/(TP+FN); 1.0 when there are no positives to catch.
         *       - fp_rate   = FP/(FP+TN); 0.0 when there is nothing that could be falsely flagged.
         *       - precision = TP/(TP+FP); 1.0 when nothing was flagged.
         */
        Confusion: {
            /**
             * Fn
             * @default 0
             */
            fn: number;
            /**
             * Fp
             * @default 0
             */
            fp: number;
            /** Fp Rate */
            readonly fp_rate: number;
            /** Precision */
            readonly precision: number;
            /** Recall */
            readonly recall: number;
            /**
             * Tn
             * @default 0
             */
            tn: number;
            /**
             * Tp
             * @default 0
             */
            tp: number;
        };
        /**
         * ConsoleConfig
         * @description Everything the UI needs to decide what to show and what to hide.
         *
         *     `read_only` drives affordances: the console hides write controls rather than letting a user
         *     discover the 403 by clicking. The guard still runs server-side — this is presentation only.
         */
        ConsoleConfig: {
            /** Backends */
            backends: components["schemas"]["BackendInfo"][];
            /** Default Base */
            default_base: string;
            /** Practice Mode */
            practice_mode: boolean;
            principal: components["schemas"]["Principal"];
            /** Read Only */
            read_only: boolean;
            /** Runs Dir */
            runs_dir: string;
            /** Skills Repo */
            skills_repo: string;
            /** Skills Root */
            skills_root: string;
        };
        /**
         * Decision
         * @description What a human decided about one candidate, and where it ended up.
         */
        Decision: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Branch */
            branch?: string | null;
            /** Case Id */
            case_id?: string | null;
            /** Commit */
            commit?: string | null;
            /**
             * Principal
             * @default
             */
            principal: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Skill Id */
            skill_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "promoted" | "rejected";
        };
        /** DecisionResponse */
        DecisionResponse: {
            /** Candidate Id */
            candidate_id: string;
            decision: components["schemas"]["Decision"];
        };
        /** EvalCase */
        EvalCase: {
            change: components["schemas"]["CodeChange"];
            /** Expect */
            expect: components["schemas"]["Expectation"][];
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "should_catch" | "should_not_flag";
            /**
             * @default {
             *       "source": "manual"
             *     }
             */
            provenance: components["schemas"]["Provenance"];
        };
        /**
         * Expectation
         * @description One assertion about a change: something a reviewer must (or must not) surface.
         */
        Expectation: {
            /** Id */
            id: string;
            /**
             * Must
             * @enum {string}
             */
            must: "appear" | "not_appear";
            /** Pattern */
            pattern?: string | null;
            /**
             * Semantic
             * @default
             */
            semantic: string;
            severity_min?: components["schemas"]["Severity"] | null;
            where: components["schemas"]["Region"];
        };
        /**
         * ExpectationOutcome
         * @description How one expectation resolved in one trial, with the evidence behind it.
         *
         *     The expectation is copied in, not just referenced by id. A record has to be readable on its own:
         *     the skill may have been edited since, and "expectation e1 failed" is unusable without knowing
         *     what e1 asserted — the whole point of the drill-down is deciding whether the *judge* was right,
         *     which is impossible without the text it judged against.
         *
         *     `eligible_finding_indices` are the findings that survived the structural prefilter (same file,
         *     within the line range, meeting severity_min). `verdicts` covers only those actually judged —
         *     matching short-circuits at the first match, so a trailing eligible finding may have no verdict.
         *     That asymmetry is deliberate: recording must not add LLM calls.
         */
        ExpectationOutcome: {
            /**
             * Eligible Finding Indices
             * @default []
             */
            eligible_finding_indices: number[];
            /** Expectation Id */
            expectation_id: string;
            /**
             * Must
             * @enum {string}
             */
            must: "appear" | "not_appear";
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "tp" | "fn" | "fp" | "tn";
            /**
             * Semantic
             * @default
             */
            semantic: string;
            severity_min?: components["schemas"]["Severity"] | null;
            /**
             * Verdicts
             * @default []
             */
            verdicts: components["schemas"]["JudgeVerdictRecord"][];
            where?: components["schemas"]["Region"] | null;
        };
        /** FileChange */
        FileChange: {
            /**
             * Added
             * @default []
             */
            added: components["schemas"]["AddedLine"][];
            /** Old Path */
            old_path?: string | null;
            /** Path */
            path: string;
            /**
             * Raw Diff
             * @default
             */
            raw_diff: string;
        };
        /**
         * Finding
         * @description A single issue a reviewer raised while running a skill over a change.
         */
        Finding: {
            /** Confidence */
            confidence?: number | null;
            /** Line */
            line?: number | null;
            /**
             * Message
             * @default
             */
            message: string;
            /** Path */
            path: string;
            /** Rule Id */
            rule_id?: string | null;
            /** @default 20 */
            severity: components["schemas"]["Severity"];
            /** Skill Id */
            skill_id: string;
        };
        /**
         * GateConfig
         * @description Tolerances for promoting a skill change. Defaults are strict: no recall loss, no new false
         *     positives, no case that used to pass may start failing.
         */
        GateConfig: {
            /**
             * Case Fp Ceiling
             * @default 0.001
             */
            case_fp_ceiling: number;
            /**
             * Case Recall Floor
             * @default 0.999
             */
            case_recall_floor: number;
            /**
             * Fp Tol
             * @default 0
             */
            fp_tol: number;
            /**
             * Max Case Regressions
             * @default 0
             */
            max_case_regressions: number;
            /**
             * Recall Tol
             * @default 0
             */
            recall_tol: number;
            /**
             * Targeted Cases
             * @default []
             */
            targeted_cases: string[];
        };
        /**
         * GateRecord
         * @description One comparison of a candidate skill against a baseline, and what it was run against.
         */
        GateRecord: {
            /**
             * Backend
             * @default
             */
            backend: string;
            /** Base Hash */
            base_hash: string;
            /**
             * Base Ref
             * @default
             */
            base_ref: string;
            base_score: components["schemas"]["SkillScore"];
            /** Candidate Hash */
            candidate_hash: string;
            /**
             * Candidate Ref
             * @default
             */
            candidate_ref: string;
            candidate_score: components["schemas"]["SkillScore"];
            /**
             * @default {
             *       "case_fp_ceiling": 0.001,
             *       "case_recall_floor": 0.999,
             *       "fp_tol": 0,
             *       "max_case_regressions": 0,
             *       "recall_tol": 0,
             *       "targeted_cases": []
             *     }
             */
            config: components["schemas"]["GateConfig"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Duration S
             * @default 0
             */
            duration_s: number;
            /** Id */
            id: string;
            /**
             * K
             * @default 1
             */
            k: number;
            /**
             * Llm Calls
             * @default 0
             */
            llm_calls: number;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Practice Mode
             * @default false
             */
            practice_mode: boolean;
            /**
             * Principal
             * @default
             */
            principal: string;
            result: components["schemas"]["GateResult"];
            /** Skill Id */
            skill_id: string;
        };
        /** GateResult */
        GateResult: {
            /**
             * Fixed Cases
             * @default []
             */
            fixed_cases: string[];
            /** Fp Rate New */
            fp_rate_new: number;
            /** Fp Rate Old */
            fp_rate_old: number;
            /** Passed */
            passed: boolean;
            /** Reasons */
            reasons: string[];
            /** Recall New */
            recall_new: number;
            /** Recall Old */
            recall_old: number;
            /** Regressed Cases */
            regressed_cases: string[];
            /**
             * Unfixed Cases
             * @default []
             */
            unfixed_cases: string[];
        };
        /**
         * GitState
         * @description Repo state. `available` is false when the skills root isn't a git checkout at all — the
         *     console still works read-only, it just can't propose anything.
         */
        GitState: {
            /** Available */
            available: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            status?: components["schemas"]["RepoStatus"] | null;
        };
        /** GuidanceRequest */
        GuidanceRequest: {
            edit: components["schemas"]["SkillEdit"];
            /** Expect Head */
            expect_head?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JudgeVerdictRecord
         * @description One judge call: which finding was judged against an expectation, and what it decided.
         */
        JudgeVerdictRecord: {
            /** Confidence */
            confidence: number;
            /** Finding Index */
            finding_index: number;
            /** Matched */
            matched: boolean;
            /** Reason */
            reason: string;
        };
        /** MetaRequest */
        MetaRequest: {
            /** Expect Head */
            expect_head?: string | null;
            /** Meta Yaml */
            meta_yaml: string;
        };
        /**
         * PreparedCase
         * @description A validated case, ready to write. `files` are repo-relative paths → contents.
         */
        PreparedCase: {
            case: components["schemas"]["EvalCase"];
            /** Case Id */
            case_id: string;
            /** Files */
            files: {
                [key: string]: string;
            };
            /** Skill Id */
            skill_id: string;
        };
        /**
         * PreparedSkill
         * @description A validated guidance edit, ready to commit. `files` are repo-relative paths → contents.
         */
        PreparedSkill: {
            /** Files */
            files: {
                [key: string]: string;
            };
            /**
             * Guidance Changed
             * @description Whether this edit invalidates an existing gate result.
             *
             *     `skill_hash` covers the guidance body and the eval cases — the things that determine a
             *     score. Renaming a skill or fixing a typo in its description leaves it unchanged, and
             *     correctly so: neither can alter what the reviewer does, so neither should force a re-gate.
             */
            readonly guidance_changed: boolean;
            /** Previous Hash */
            previous_hash: string;
            skill: components["schemas"]["Skill"];
            /** Skill Hash */
            skill_hash: string;
            /** Skill Id */
            skill_id: string;
            /** Version */
            version: number;
        };
        /**
         * Principal
         * @description Who the console is acting as. Recorded on runs and used to author commits.
         */
        Principal: {
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Mode
             * @default local
             * @enum {string}
             */
            mode: "local" | "proxy" | "anonymous";
            /** Name */
            name: string;
        };
        /** PromoteRequest */
        PromoteRequest: {
            edits: components["schemas"]["CaseEdits"];
        };
        /** PromoteResponse */
        PromoteResponse: {
            /** Batch Commits */
            batch_commits: number;
            /** Branch */
            branch: string;
            /** Candidate Id */
            candidate_id: string;
            /** Commit */
            commit: string;
            prepared: components["schemas"]["PreparedCase"];
        };
        /**
         * Proposal
         * @description The state of a skill's pending guidance change, and whether it may be published.
         */
        Proposal: {
            /** Base */
            base: string;
            /**
             * Body
             * @default
             */
            body: string;
            /** Branch */
            branch: string;
            /** Commits */
            commits: number;
            /**
             * Diff
             * @default
             */
            diff: string;
            /** Head */
            head?: string | null;
            /** Path */
            path: string;
            /** Skill Hash */
            skill_hash: string;
            /** Skill Id */
            skill_id: string;
            /** Staged */
            staged: boolean;
            verdict: components["schemas"]["Verdict"];
            /** Version */
            version: number;
        };
        /** ProposeRequest */
        ProposeRequest: {
            /** Branch */
            branch: string;
        };
        /** ProposeResponse */
        ProposeResponse: {
            /** Branch */
            branch: string;
            /** Merge Request Url */
            merge_request_url?: string | null;
            /**
             * Message
             * @default
             */
            message: string;
            /** Pushed */
            pushed: boolean;
            /** Remote */
            remote: string;
        };
        /**
         * Provenance
         * @description Where an eval case came from — every case must be traceable to a signal.
         */
        Provenance: {
            /** Human Signal */
            human_signal?: string | null;
            /** Ref */
            ref?: string | null;
            /**
             * Source
             * @default manual
             */
            source: string;
        };
        /** Queue */
        Queue: {
            /** Available */
            available: boolean;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Items */
            items: components["schemas"]["QueueItem"][];
            /** Root */
            root: string;
        };
        /**
         * QueueItem
         * @description A candidate plus the pre-filled edit form the console opens with.
         */
        QueueItem: {
            edits: components["schemas"]["CaseEdits"];
            entry: components["schemas"]["CandidateEntry"];
        };
        /**
         * Reference
         * @description A resolvable, drift-checkable pointer — code path or wiki doc, not copied text.
         */
        Reference: {
            /** Id */
            id?: string | null;
            /** Kind */
            kind: string;
            /** Path */
            path?: string | null;
            /** Repo */
            repo?: string | null;
        };
        /**
         * Region
         * @description A location in the change: a file path and an optional inclusive line range.
         */
        Region: {
            /** Line Range */
            line_range?: [
                number,
                number
            ] | null;
            /** Path */
            path: string;
        };
        /** RejectRequest */
        RejectRequest: {
            /** Reason */
            reason: string;
        };
        /**
         * RepoRef
         * @description Provider-neutral repository reference, e.g. ``gitlab:acme/payments``.
         */
        RepoRef: {
            /** Path */
            path: string;
            /** Provider */
            provider: string;
        };
        /** RepoStatus */
        RepoStatus: {
            /** Branch */
            branch: string;
            /** Clean */
            clean: boolean;
            /**
             * Dirty Paths
             * @default []
             */
            dirty_paths: string[];
            /** Head */
            head: string;
            /** Remote */
            remote?: string | null;
        };
        /**
         * RunListItem
         * @description A run summary plus whether its version is trustworthy as a comparison key.
         *
         *     `stale_version` means another run shares this `skill_version` with different content — the two
         *     look comparable and are not.
         */
        RunListItem: {
            /**
             * Stale Version
             * @default false
             */
            stale_version: boolean;
            summary: components["schemas"]["RunSummary"];
        };
        /**
         * RunRecord
         * @description One complete eval run: what was run, against what, by whom, and everything it produced.
         */
        RunRecord: {
            /**
             * Backend
             * @default
             */
            backend: string;
            /**
             * Cases
             * @default []
             */
            cases: components["schemas"]["CaseRun"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Duration S
             * @default 0
             */
            duration_s: number;
            /** Git Ref */
            git_ref?: string | null;
            /** Id */
            id: string;
            /**
             * Judge Effort
             * @default medium
             */
            judge_effort: string;
            /**
             * K
             * @default 1
             */
            k: number;
            /**
             * Llm Calls
             * @default 0
             */
            llm_calls: number;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Practice Mode
             * @default false
             */
            practice_mode: boolean;
            /**
             * Principal
             * @default
             */
            principal: string;
            /**
             * Reviewer Effort
             * @default high
             */
            reviewer_effort: string;
            score: components["schemas"]["SkillScore"];
            /** Skill Hash */
            skill_hash: string;
            /** Skill Id */
            skill_id: string;
            /** Skill Version */
            skill_version: number;
        };
        /**
         * RunSummary
         * @description Index row — enough to list and chart runs without loading full records.
         */
        RunSummary: {
            /**
             * Backend
             * @default
             */
            backend: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Duration S
             * @default 0
             */
            duration_s: number;
            /**
             * F2
             * @default 0
             */
            f2: number;
            /**
             * Fp Rate
             * @default 0
             */
            fp_rate: number;
            /** Id */
            id: string;
            /**
             * K
             * @default 1
             */
            k: number;
            /**
             * Llm Calls
             * @default 0
             */
            llm_calls: number;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Practice Mode
             * @default false
             */
            practice_mode: boolean;
            /**
             * Precision
             * @default 0
             */
            precision: number;
            /**
             * Recall
             * @default 0
             */
            recall: number;
            /** Skill Hash */
            skill_hash: string;
            /** Skill Id */
            skill_id: string;
            /** Skill Version */
            skill_version: number;
        };
        /**
         * Severity
         * @description Ordered so `>=` comparisons express a minimum-severity threshold.
         * @enum {integer}
         */
        Severity: 10 | 20 | 30;
        /** Skill */
        Skill: {
            /**
             * Body
             * @default
             */
            body: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Eval Cases
             * @default []
             */
            eval_cases: components["schemas"]["EvalCase"][];
            /** Id */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Owner
             * @default
             */
            owner: string;
            /**
             * Provenance
             * @default {}
             */
            provenance: {
                [key: string]: components["schemas"]["Provenance"][];
            };
            /**
             * References
             * @default []
             */
            references: components["schemas"]["Reference"][];
            /**
             * @default {
             *       "labels": [],
             *       "paths": []
             *     }
             */
            triggers: components["schemas"]["Triggers"];
            /**
             * Version
             * @default 1
             */
            version: number;
        };
        /** SkillDetail */
        SkillDetail: {
            /**
             * Cases
             * @default []
             */
            cases: components["schemas"]["CaseSummary"][];
            /**
             * Has Runs
             * @default false
             */
            has_runs: boolean;
            /**
             * Precision Evidence
             * @default {}
             */
            precision_evidence: {
                [key: string]: number;
            };
            /**
             * Rules
             * @default []
             */
            rules: string[];
            /**
             * Runs
             * @default []
             */
            runs: components["schemas"]["RunSummary"][];
            skill: components["schemas"]["Skill"];
            /**
             * Untested Rules
             * @default []
             */
            untested_rules: string[];
        };
        /**
         * SkillEdit
         * @description A human's rewrite of a skill's guidance.
         *
         *     Only the fields a person edits as prose. Everything else in the frontmatter — `id`, `triggers`,
         *     anything an operator hand-added — is carried through untouched, which is why the editor can be a
         *     plain markdown box rather than a form that has to know every key.
         */
        SkillEdit: {
            /** Body */
            body: string;
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
        };
        /** SkillScore */
        SkillScore: {
            /** Cases */
            cases: components["schemas"]["CaseScore"][];
            readonly confusion: components["schemas"]["Confusion"];
            /**
             * F2
             * @description The recall-favouring composite, serialized. `f_beta()` covers other betas.
             */
            readonly f2: number;
            /** Fp Rate */
            readonly fp_rate: number;
            /** Fp Rate Stdev */
            readonly fp_rate_stdev: number;
            /** K */
            k: number;
            /** Precision */
            readonly precision: number;
            /** Recall */
            readonly recall: number;
            /** Recall Stdev */
            readonly recall_stdev: number;
            /** Skill Id */
            skill_id: string;
            /** Version */
            version: number;
        };
        /**
         * SkillSummary
         * @description A skill as it appears on the index, with just enough history to rank and chart it.
         */
        SkillSummary: {
            /**
             * Catch Cases
             * @default 0
             */
            catch_cases: number;
            /**
             * Description
             * @default
             */
            description: string;
            /** Id */
            id: string;
            latest?: components["schemas"]["RunSummary"] | null;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Noflag Cases
             * @default 0
             */
            noflag_cases: number;
            /**
             * Owner
             * @default
             */
            owner: string;
            /**
             * Precision Evidence
             * @default {}
             */
            precision_evidence: {
                [key: string]: number;
            };
            /**
             * Recall Trend
             * @default []
             */
            recall_trend: number[];
            /**
             * Stale Version
             * @default false
             */
            stale_version: boolean;
            /** Version */
            version: number;
        };
        /**
         * StagedSkill
         * @description What a save produced, plus the proposal state it left behind.
         *
         *     The proposal is included so the editor can grey out *Propose* in the same round trip that saved
         *     the edit — the moment when it is most important to say that the guidance now needs a gate.
         */
        StagedSkill: {
            /** Branch */
            branch: string;
            /** Commit */
            commit: string;
            prepared: components["schemas"]["PreparedSkill"];
            proposal: components["schemas"]["Proposal"];
        };
        /**
         * TrialRecord
         * @description One reviewer pass over one case: everything it said, and how each expectation resolved.
         */
        TrialRecord: {
            /**
             * Findings
             * @default []
             */
            findings: components["schemas"]["Finding"][];
            /** Index */
            index: number;
            /**
             * Outcomes
             * @default []
             */
            outcomes: components["schemas"]["ExpectationOutcome"][];
        };
        /** Triggers */
        Triggers: {
            /**
             * Labels
             * @default []
             */
            labels: string[];
            /**
             * Paths
             * @default []
             */
            paths: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Verdict
         * @description C6 applied to one version of a skill: may it be published, and on what evidence?
         */
        Verdict: {
            /** Can Propose */
            can_propose: boolean;
            /**
             * Caveat
             * @default
             */
            caveat: string;
            evidence?: components["schemas"]["GateRecord"] | null;
            latest?: components["schemas"]["GateRecord"] | null;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_candidates_api_candidates_get: {
        parameters: {
            query?: {
                include_decided?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Queue"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_api_candidates_batch_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
        };
    };
    get_candidate_api_candidates__candidate_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_api_candidates__candidate_id__decision_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_promotion_api_candidates__candidate_id__preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreparedCase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_api_candidates__candidate_id__promote_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_candidates__candidate_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_console_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsoleConfig"];
                };
            };
        };
    };
    propose_api_git_propose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_git_status_api_git_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitState"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                skill_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_report_api_runs__run_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_api_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillSummary"][];
                };
            };
        };
    };
    get_skill_api_skills__skill_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_api_skills__skill_id__cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_guidance_api_skills__skill_id__guidance_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuidanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagedSkill"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_guidance_api_skills__skill_id__guidance_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuidanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreparedSkill"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_meta_api_skills__skill_id__meta_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagedSkill"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_proposal_api_skills__skill_id__proposal_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
